"""Constants for the mir_meter integration."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Final

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
    EntityCategory,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

DOMAIN = "mir_meter"
SCAN_INTERVAL = timedelta(seconds=60)

KILO_VOLT_AMPERE: Final = "kVA"
KILO_VOLT_AMPERE_REACTIVE: Final = "kvar"
KILO_VOLT_AMPERE_REACTIVE_HOUR: Final = "kvarh"


@dataclass
class MirMeterSensorEntityDescription(SensorEntityDescription):
    """Describes Iammeter sensor entity."""

    value: Callable[[float | int], float] | Callable[[datetime], datetime] | None = None


SENSOR_TYPES: tuple[MirMeterSensorEntityDescription, ...] = (
    MirMeterSensorEntityDescription(
        key="1.0.1.8.0.255",
        translation_key="positive_active_energy_total",
        icon="mdi:meter-electric-outline",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.8.1.255",
        translation_key="positive_active_energy_tariff_1",
        icon="mdi:meter-electric-outline",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.8.2.255",
        translation_key="positive_active_energy_tariff_2",
        icon="mdi:meter-electric-outline",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.0.9.1.255",
        translation_key="current_time",
        icon="mdi:clock-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.0.9.2.255",
        translation_key="current_date",
        icon="mdi:calendar",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.31.7.0.255",
        translation_key="instantaneous_current_of_phase_a",
        icon="mdi:current-ac",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.CURRENT,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.32.7.0.255",
        translation_key="instantaneous_voltage_of_phase_a",
        icon="mdi:lightning-bolt-outline",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.VOLTAGE,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.13.7.0.255",
        translation_key="instantaneous_total_power_factor",
        icon="mdi:scale-balance",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.131.7.0.255",
        translation_key="instantaneous_total_reactive_power_factor",
        icon="mdi:scale-balance",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.14.7.0.255",
        translation_key="mains_frequency",
        icon="mdi:sine-wave",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.FREQUENCY,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.9.0.255",
        translation_key="current_temperature",
        icon="mdi:thermometer-lines",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.9.7.0.255",
        translation_key="instantaneous_apparent_power",
        icon="mdi:home-lightning-bolt-outline",
        native_unit_of_measurement=KILO_VOLT_AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.APPARENT_POWER,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.7.0.255",
        translation_key="instantaneous_active_power",
        icon="mdi:home-lightning-bolt-outline",
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.POWER,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.3.7.0.255",
        translation_key="instantaneous_reactive_power",
        icon="mdi:home-lightning-bolt-outline",
        native_unit_of_measurement=KILO_VOLT_AMPERE_REACTIVE,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.REACTIVE_POWER,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.2.8.0.255",
        translation_key="negative_active_energy_total",
        icon="mdi:home-export-outline",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.3.8.0.255",
        translation_key="positive_reactive_energy_total",
        icon="mdi:home-import-outline",
        native_unit_of_measurement=KILO_VOLT_AMPERE_REACTIVE_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.4.8.0.255",
        translation_key="negative_reactive_energy_total",
        icon="mdi:home-export-outline",
        native_unit_of_measurement=KILO_VOLT_AMPERE_REACTIVE_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.8.0.255",
        translation_key="total_operation_time",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.17.0.255",
        translation_key="pm_positive_active_energy_total",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.17.1.255",
        translation_key="pm_positive_active_energy_tariff_1",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.17.2.255",
        translation_key="pm_positive_active_energy_tariff_2",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.17.3.255",
        translation_key="pm_positive_active_energy_tariff_3",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.1.17.4.255",
        translation_key="pm_positive_active_energy_tariff_4",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.2.17.0.255",
        translation_key="pm_negative_active_energy_total",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.3.17.0.255",
        translation_key="pm_positive_reactive_energy_total",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=KILO_VOLT_AMPERE_REACTIVE_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.4.17.0.255",
        translation_key="pm_negative_reactive_energy_total",
        icon="mdi:calendar-arrow-left",
        native_unit_of_measurement=KILO_VOLT_AMPERE_REACTIVE_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        device_class=SensorDeviceClass.ENERGY,
        entity_registry_enabled_default=False,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.1.0.255",
        translation_key="factory_number",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.22.0.0.255",
        translation_key="network_address",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.2.5.255",
        translation_key="verification_date",
        icon="mdi:calendar-check-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="1.0.0.2.128.255",
        translation_key="communication_software_version",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.1.2.255",
        translation_key="metrological_software_version",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.128.0.1.255",
        translation_key="plc_module_software_version",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.128.3.1.255",
        translation_key="zigbee_module_software_version",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.128.5.10.255",
        translation_key="gsm_signal_level",
        icon="mdi:signal",
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    MirMeterSensorEntityDescription(
        key="0.0.96.1.6.255",
        translation_key="spodes_specification_version",
        icon="mdi:information-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
)
